/**
 * Ensure .rclaude/ directory exists in the given CWD with a .gitignore.
 * Returns the absolute path to the directory.
 */

import { existsSync, mkdirSync, renameSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

export function ensureRclaudeDir(cwd: string): string {
  const dir = join(cwd, '.rclaude')

  // Migrate tasks/ -> project/ if old name exists
  const oldTasks = join(dir, 'tasks')
  const newProject = join(dir, 'project')
  if (existsSync(oldTasks) && !existsSync(newProject)) {
    renameSync(oldTasks, newProject)
  }

  mkdirSync(join(dir, 'settings'), { recursive: true })
  mkdirSync(join(dir, 'project'), { recursive: true })

  const gitignorePath = join(dir, '.gitignore')
  if (!existsSync(gitignorePath)) {
    writeFileSync(
      gitignorePath,
      '# Auto-generated by rclaude\n# Session temp files\nsettings/\n\n# Keep project board and config committed\n!project/\n!rclaude.json\n',
    )
  }
  return dir
}
