/**
 * Funny session name generator.
 * Produces memorable two-word names like "quantum-muffin" or "turbo-badger".
 * Used for spawned/revived sessions so they're easy to identify and resume.
 */

const ADJECTIVES = [
  'atomic',
  'binary',
  'blazing',
  'chaotic',
  'cosmic',
  'cranky',
  'crunchy',
  'cursed',
  'cyber',
  'dapper',
  'defiant',
  'dizzy',
  'doom',
  'drunken',
  'dusty',
  'elastic',
  'epic',
  'feral',
  'fizzy',
  'fluffy',
  'foggy',
  'frozen',
  'funky',
  'fuzzy',
  'galactic',
  'ghostly',
  'giga',
  'gnarly',
  'golden',
  'greasy',
  'grumpy',
  'haunted',
  'hyper',
  'iron',
  'janky',
  'jolly',
  'jumpy',
  'laser',
  'lucky',
  'lumpy',
  'magic',
  'mega',
  'molten',
  'mystic',
  'neon',
  'ninja',
  'noble',
  'nuclear',
  'omega',
  'pixel',
  'plasma',
  'plucky',
  'polar',
  'primal',
  'punk',
  'quantum',
  'radical',
  'raging',
  'rapid',
  'rebel',
  'rogue',
  'rusty',
  'savage',
  'shadow',
  'shady',
  'silent',
  'slick',
  'sneaky',
  'solar',
  'sonic',
  'spicy',
  'stealth',
  'stellar',
  'stormy',
  'strange',
  'super',
  'swamp',
  'techno',
  'thunder',
  'toxic',
  'turbo',
  'ultra',
  'undead',
  'velvet',
  'viral',
  'void',
  'volatile',
  'warp',
  'wicked',
  'wild',
  'zero',
  'zippy',
]

const NOUNS = [
  'alpaca',
  'anvil',
  'badger',
  'bagel',
  'banana',
  'beacon',
  'biscuit',
  'blob',
  'bobcat',
  'bolt',
  'bucket',
  'cactus',
  'cannon',
  'cobra',
  'comet',
  'condor',
  'cookie',
  'coral',
  'crane',
  'dagger',
  'disco',
  'donkey',
  'dragon',
  'falcon',
  'ferret',
  'flamingo',
  'gadget',
  'gecko',
  'gopher',
  'gorilla',
  'gremlin',
  'hammer',
  'hawk',
  'hedgehog',
  'hippo',
  'hornet',
  'igloo',
  'jackal',
  'jaguar',
  'kebab',
  'koala',
  'kraken',
  'lemur',
  'llama',
  'lobster',
  'mammoth',
  'mantis',
  'marlin',
  'marmot',
  'moose',
  'muffin',
  'narwhal',
  'newt',
  'nugget',
  'orca',
  'osprey',
  'otter',
  'panda',
  'parrot',
  'pelican',
  'penguin',
  'phoenix',
  'pickle',
  'pigeon',
  'piranha',
  'piston',
  'platypus',
  'possum',
  'pretzel',
  'puffin',
  'python',
  'quail',
  'raccoon',
  'raptor',
  'raven',
  'rhino',
  'rocket',
  'salmon',
  'scarab',
  'scorpion',
  'seagull',
  'shark',
  'sloth',
  'sphinx',
  'squid',
  'stork',
  'taco',
  'tiger',
  'toucan',
  'trout',
  'turtle',
  'viper',
  'vulture',
  'walrus',
  'wasp',
  'weasel',
  'wizard',
  'wombat',
  'yak',
  'zebra',
]

/** Total possible combinations: ~90 * ~95 = ~8,550 unique names */

/**
 * Generate a random session name.
 * @param usedNames - Set of names already in use (to avoid collisions)
 * @param maxRetries - Maximum collision retries before appending a number
 * @returns A unique funny name like "quantum-muffin"
 */
export function generateConversationName(usedNames?: Set<string>, maxRetries = 10): string {
  for (let i = 0; i < maxRetries; i++) {
    const adj = ADJECTIVES[Math.floor(Math.random() * ADJECTIVES.length)]
    const noun = NOUNS[Math.floor(Math.random() * NOUNS.length)]
    const name = `${adj}-${noun}`
    if (!usedNames || !usedNames.has(name)) return name
  }
  // Exhausted retries -- append random number to guarantee uniqueness
  const adj = ADJECTIVES[Math.floor(Math.random() * ADJECTIVES.length)]
  const noun = NOUNS[Math.floor(Math.random() * NOUNS.length)]
  return `${adj}-${noun}-${Math.floor(Math.random() * 999)}`
}
