// Auto-generated by scripts/gen-version.ts - do not edit
// Type is defined here so consumers get proper types even from stale stubs
export interface BuildVersion {
  gitHash: string
  gitHashShort: string
  buildTime: string
  dirty: boolean
  recentCommits: Array<{ hash: string; message: string }>
}

export const BUILD_VERSION: BuildVersion = {
  gitHash: '44c7b737d247001e09990e86eb5e5e30f1cfffed',
  gitHashShort: '44c7b73-dirty',
  buildTime: '2026-03-26T14:00:48.351Z',
  dirty: true,
  recentCommits: [{"hash":"44c7b73","message":"(HEAD -> main, origin/main, origin/HEAD) feat: Context window usage bar in session sidebar"},{"hash":"fc5e7e6","message":"feat: Rich permission dialog with tool-specific formatting"},{"hash":"d9e8494","message":"fix: Allow clearing project icon/label/color on save"}],
}
