// Auto-generated by scripts/gen-version.ts - do not edit
// Type is defined here so consumers get proper types even from stale stubs
export interface BuildVersion {
  gitHash: string
  gitHashShort: string
  buildTime: string
  dirty: boolean
  recentCommits: Array<{ hash: string; message: string }>
}

export const BUILD_VERSION: BuildVersion = {
  gitHash: 'e97f67e9f7519abc1487452f8e4cfd5a9a0b89a6',
  gitHashShort: 'e97f67e-dirty',
  buildTime: '2026-03-13T15:50:11.885Z',
  dirty: true,
  recentCommits: [
    { hash: 'e97f67e', message: '(HEAD -> main, origin/main, origin/HEAD) chore: Update build version' },
    { hash: 'cad17dc', message: 'feat: Per-subagent token usage tracking and display' },
    { hash: '4d62e78', message: 'fix: Eliminate Zustand re-render storms causing React error #185 and UI jank' },
  ],
}
