// Auto-generated by scripts/gen-version.ts - do not edit
// Type is defined here so consumers get proper types even from stale stubs
export interface BuildVersion {
  gitHash: string
  gitHashShort: string
  buildTime: string
  dirty: boolean
  recentCommits: Array<{ hash: string; message: string }>
}

export const BUILD_VERSION: BuildVersion = {
  gitHash: '53302af251db4690a8058eb556ac45db082e7344',
  gitHashShort: '53302af-dirty',
  buildTime: '2026-03-27T02:25:25.185Z',
  dirty: true,
  recentCommits: [{"hash":"53302af","message":"(HEAD -> main, origin/main, origin/HEAD) fix: Version mismatch check ignores -dirty suffix"},{"hash":"3512b92","message":"fix: Resolve all biome lint issues and last TS error"},{"hash":"44c7b73","message":"feat: Context window usage bar in session sidebar"}],
}
