#!/usr/bin/env bun
/**
 * Generate src/shared/version.ts with git hash and build time.
 * Run before compiling binaries. Falls back gracefully when git is unavailable (e.g. Docker).
 */
import { execSync } from 'node:child_process'
import { join } from 'node:path'

const ROOT = join(import.meta.dir, '..')
const OUT = join(ROOT, 'src', 'shared', 'version.ts')

let gitHash = 'unknown'
let dirty = false
try {
  gitHash = execSync('git rev-parse HEAD', { cwd: ROOT, stdio: ['pipe', 'pipe', 'pipe'] })
    .toString()
    .trim()
  // Exclude version.ts from dirty check (it's always modified by this script)
  const porcelain = execSync('git status --porcelain', { cwd: ROOT, stdio: ['pipe', 'pipe', 'pipe'] })
    .toString()
    .trim()
  dirty = porcelain.split('\n').some(line => line.trim() && !line.includes('src/shared/version.ts'))
} catch {
  // No git available (Docker build, CI, etc.).
  // Prefer env vars supplied by the Docker build wrapper -- this is what
  // scripts/docker-build-broker.sh passes through as --build-arg.
  if (process.env.GIT_COMMIT && process.env.GIT_COMMIT !== 'unknown') {
    gitHash = process.env.GIT_COMMIT
    dirty = (process.env.GIT_COMMIT_SHORT ?? '').endsWith('-dirty')
  } else {
    // If version.ts already has a real hash (pre-generated on host), keep it
    try {
      const existing = await Bun.file(OUT).text()
      if (existing.includes("gitHash: '") && !existing.includes("gitHash: 'unknown'")) {
        console.log('[version] No git, keeping pre-generated version.ts')
        process.exit(0)
      }
    } catch {
      // File doesn't exist yet, continue with 'unknown'
    }
  }
}

const gitHashShort = gitHash === 'unknown' ? 'unknown' : gitHash.slice(0, 7)
const buildTime = new Date().toISOString()

let recentCommits: Array<{ hash: string; message: string }> = []
try {
  const log = execSync('git log --oneline -3', { cwd: ROOT, stdio: ['pipe', 'pipe', 'pipe'] })
    .toString()
    .trim()
  recentCommits = log.split('\n').map(line => {
    const spaceIdx = line.indexOf(' ')
    return { hash: line.slice(0, spaceIdx), message: line.slice(spaceIdx + 1) }
  })
} catch {
  // No git
}

// Capture the current branch and its upstream GitHub owner/repo so the
// compiled binary can check for updates without any local git state.
let branch = 'main'
let githubRepo = ''
try {
  branch =
    execSync('git branch --show-current', { cwd: ROOT, stdio: ['pipe', 'pipe', 'pipe'] })
      .toString()
      .trim() || 'main'

  // Find the remote tracking this branch (e.g. "origin")
  let remote = ''
  try {
    remote = execSync(`git config branch.${branch}.remote`, { cwd: ROOT, stdio: ['pipe', 'pipe', 'pipe'] })
      .toString()
      .trim()
  } catch {
    remote = 'origin'
  }

  const remoteUrl = execSync(`git remote get-url ${remote}`, { cwd: ROOT, stdio: ['pipe', 'pipe', 'pipe'] })
    .toString()
    .trim()

  // Parse owner/repo from git@github.com:owner/repo.git or https://github.com/owner/repo.git
  const sshMatch = remoteUrl.match(/github\.com[:/]([^/]+\/[^/]+?)(?:\.git)?$/)
  if (sshMatch) githubRepo = sshMatch[1]
} catch {
  // No git or no remote
}

const content = `// Auto-generated by scripts/gen-version.ts - do not edit
// Type is defined here so consumers get proper types even from stale stubs
export interface BuildVersion {
  gitHash: string
  gitHashShort: string
  buildTime: string
  dirty: boolean
  branch: string
  githubRepo: string
  recentCommits: Array<{ hash: string; message: string }>
}

export const BUILD_VERSION: BuildVersion = {
  gitHash: '${gitHash}',
  gitHashShort: '${gitHashShort}${dirty ? '-dirty' : ''}',
  buildTime: '${buildTime}',
  dirty: ${dirty},
  branch: '${branch}',
  githubRepo: '${githubRepo}',
  recentCommits: ${JSON.stringify(recentCommits)},
}
`

await Bun.write(OUT, content)
console.log(`[version] ${gitHashShort}${dirty ? '-dirty' : ''} @ ${buildTime}`)
