#!/usr/bin/env bun
/**
 * Generate src/shared/version.ts with git hash and build time.
 * Run before compiling binaries.
 */
import { execSync } from 'node:child_process'
import { join } from 'node:path'

const ROOT = join(import.meta.dir, '..')
const OUT = join(ROOT, 'src', 'shared', 'version.ts')

const gitHash = execSync('git rev-parse HEAD', { cwd: ROOT }).toString().trim()
const gitHashShort = gitHash.slice(0, 7)
const dirty = execSync('git status --porcelain', { cwd: ROOT }).toString().trim().length > 0
const buildTime = new Date().toISOString()

const content = `// Auto-generated by scripts/gen-version.ts - do not edit
export const BUILD_VERSION = {
  gitHash: '${gitHash}',
  gitHashShort: '${gitHashShort}${dirty ? '-dirty' : ''}',
  buildTime: '${buildTime}',
  dirty: ${dirty},
}
`

await Bun.write(OUT, content)
console.log(`[version] ${gitHashShort}${dirty ? '-dirty' : ''} @ ${buildTime}`)
